"""Integration-layer exports for embodied execution."""

from roboclaw.embodied.execution.integration.adapters import (
    AdapterBinding,
    AdapterCompatibilitySpec,
    AdapterHealthMode,
    AdapterLifecycleContract,
    AdapterOperation,
    AdapterRegistry,
    CompatibilityComponent,
    DEFAULT_ADAPTER_COMPATIBILITY,
    DEFAULT_ADAPTER_LIFECYCLE,
    DegradedModeSpec,
    DependencyKind,
    DependencySpec,
    EmbodiedAdapter,
    ErrorCategory,
    ErrorCodeSpec,
    OperationTimeout,
    TimeoutPolicy,
    VersionConstraint,
)
from roboclaw.embodied.execution.integration.control_surfaces import (
    ARM_HAND_CONTROL_SURFACE_PROFILE,
    EmbodimentDomain,
    ControlSurfaceKind,
    ControlSurfaceProfileRegistry,
    ControlSurfaceSpec,
    DEFAULT_CONTROL_SURFACE_PROFILES,
    DRONE_CONTROL_SURFACE_PROFILE,
    ControlSurfaceProfile,
    HUMANOID_WHOLE_BODY_CONTROL_SURFACE_PROFILE,
    MOBILE_BASE_FLEET_CONTROL_SURFACE_PROFILE,
    ObservationSurfaceSpec,
    SIMULATOR_CONTROL_SURFACE_PROFILE,
)
from roboclaw.embodied.execution.integration.carriers import ExecutionTarget
from roboclaw.embodied.execution.integration.transports import (
    Ros2ActionSpec,
    Ros2InterfaceBundle,
    Ros2ServiceSpec,
    Ros2TopicSpec,
    build_standard_ros2_contract,
    canonical_ros2_namespace,
)

__all__ = [
    "AdapterBinding",
    "AdapterCompatibilitySpec",
    "AdapterHealthMode",
    "AdapterLifecycleContract",
    "AdapterOperation",
    "AdapterRegistry",
    "ARM_HAND_CONTROL_SURFACE_PROFILE",
    "EmbodimentDomain",
    "ControlSurfaceKind",
    "ControlSurfaceProfileRegistry",
    "CompatibilityComponent",
    "ControlSurfaceSpec",
    "DEFAULT_ADAPTER_COMPATIBILITY",
    "DEFAULT_ADAPTER_LIFECYCLE",
    "DEFAULT_CONTROL_SURFACE_PROFILES",
    "DegradedModeSpec",
    "DependencyKind",
    "DependencySpec",
    "DRONE_CONTROL_SURFACE_PROFILE",
    "ControlSurfaceProfile",
    "EmbodiedAdapter",
    "ErrorCategory",
    "ErrorCodeSpec",
    "ExecutionTarget",
    "HUMANOID_WHOLE_BODY_CONTROL_SURFACE_PROFILE",
    "MOBILE_BASE_FLEET_CONTROL_SURFACE_PROFILE",
    "ObservationSurfaceSpec",
    "OperationTimeout",
    "Ros2ActionSpec",
    "Ros2InterfaceBundle",
    "Ros2ServiceSpec",
    "Ros2TopicSpec",
    "SIMULATOR_CONTROL_SURFACE_PROFILE",
    "TimeoutPolicy",
    "VersionConstraint",
    "build_standard_ros2_contract",
    "canonical_ros2_namespace",
]
